### ISSUE TITLE
Adding on top?

### ISSUE THREAD

**Issue by ebraminio** [frederikkaspar/Kaspar#2]
Hi. What is happened [here](https://fa.wikipedia.org/?diff=15570820)?

**Comment by frederikkaspar** [comment]
I think that {{جعبه اطلاعات هنرمند موسیقی was treated as stub template. Probably looking for the exact names of the templates instead of a distinct pattern would solve the problem. Another solution would be to check if the template is inserted into the second half of the page.. What do you think?

**Comment by ebraminio** [comment]
Okay, please replace `"\\n\\{\\{[^\\{\\}\\<\\>]*خرد",` with `"\\n\\{\\{(.*\\-)?(خرد|ناقص)",`. RTL editing is hard so I suggest first splitting each parameter into separate line there.

**Comment by frederikkaspar** [comment]
I pushed a new version to  src/mediawiki/task/config/ACtWPConfiguration.java . I will begin with testing soon.

**Comment by ebraminio** [comment]
Looks good, thank you. Would be nice to run carefully over previous runs.

**Comment by ebraminio** [comment]
I see you are supervising the bot edits and did some manual improvement when the bot did wrong and generally its edits looks fantastic. GJ :wave: :-)
